modLoader = "javafml"
loaderVersion = "[36,)"
license = "GNU LGPL 3.0"
[[mods]]
modId = "standardconfigs"
version = "${file.jarVersion}"
displayName = "Standard Configs"
authors = "cheaterpaul"
description = '''
Copies config files for modpacks, but does not override them
'''
[[dependencies.standardconfigs]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.standardconfigs]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5,1.17)"
ordering = "NONE"
side = "BOTH"
